CREATE DATABASE IF NOT EXISTS notes_db;

USE notes_db;

CREATE TABLE IF NOT EXISTS catatan(
  id INT AUTO_INCREMENT PRIMARY KEY,
  judul VARCHAR(255) NOT NULL,
  isi TEXT NOT NULL,
  tanggal_dibuat DATETIME DEFAULT CURRENT_TIMESTAMP,
  tanggal_diubah DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
